spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}
  secretKey: ${JWT_SECRET_KEY}
  accessExp: ${JWT_ACCESS_EXP}
  refreshExp: ${JWT_REFRESH_EXP}

coolsms:
  key: ${SMS_KEY}
  secret: ${SMS_SECRET}
  phone-number: ${SENDER_PHONE_NUMBER}

aws:
  ses:
    email: ${AWS_SES_BASE_EMAIL}
  region: ${AWS_REGION}
  credentials:
    accessKey: ${AWS_ACCESS}
    secretKey: ${AWS_SECRET}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
